mattyx14/otxserver

path_8_6x/sources/player.cpp
Con esa modificacion que le habias hecho, todos los players quedaban con green skull, independientemente lo que hagan, reloguearan etc, tenian green skull. Queda pendiente para testear mejor..
=> Skull System, green skull (?)

path_7_x/sources/spells.cpp
Con esta pequeña modificacion se soluciona el problema del exhaust en estas versiones...
=> Fix exhaust (ejemplo exura + exori vis, etc)

path_7_x/sources/player.cpp
Supongo este cambio aplica a todas las versiones.
=> Fix yellow skull

path_7_x/sources/player.cpp
Ups xD pequeño detalle, ya funciona correctamente las versiones 7x,
lamento los problemas :+1:
=> Fix crash on 7x (castSystem)

path_7_x/sources/protocolgame.cpp
Fix crash al seleccionar outfit
=> Fix crash al seleccionar outfit

path_7_x/sources/protocol.cpp
https://github.com/mattyx14/otxserver/issues/80
=> fix issuse 80

path_7_x/sources/container.cpp
Fix al bug:
https://github.com/mattyx14/otxserver/blob/otxserv2/CHANGELOG#L41
Aplicar este cambio a todos los protocolos y se soluciona este problema..
=> Fix container error https://www.youtube.com/watch?v=mJ1mydn6TjA

path_10_9/data/modules/scripts/gamestore/init.lua
Bug in action:
https://otland.net/threads/help-to-fix-bug-on-store-in-game-injection-of-points-using-wpe.248833/
Tip: Squash and merge to avoid extra "merge" commit.
=> parseTransferCoins duplicate shop coins Fix #171

path_10_9/src/iologindata.cpp
=> Added include boost/range/adaptor/reversed.hpp

path_7_7/src/player.cpp
=> Bug "stairJumpExhaustion"

.gitignore, path_10_9/src/CMakeLists.txt, path_10_9/src/account.cpp, path_10_9/src/account.h, path_10_9/src/const.h, path_10_9/src/game.cpp, path_10_9/src/player.h, path_10_9/src/protocolgame.cpp, path_10_9/src/protocolgame.h
fixes #188 
Also includes improvements to show the coin balance in market and update those numbers as they change.
=> Otxserv3 188 bug market system

path_10_9/src/game.cpp
=> Critical hit was being applied twice with a recursive call

path_10_9/src/combat.cpp, path_10_9/src/enums.h, path_10_9/src/game.cpp, path_10_9/src/player.cpp, path_10_9/src/player.h
=> new critical damage calculations

path_10_9/src/combat.cpp, path_10_9/src/enums.h, path_10_9/src/game.cpp, path_10_9/src/player.cpp, path_10_9/src/player.h
Reverts mattyx14/otxserver#235
=> Revert "new critical damage calculations"

path_10_9/src/combat.cpp, path_10_9/src/enums.h, path_10_9/src/game.cpp, path_10_9/src/player.cpp, path_10_9/src/player.h
Reverts mattyx14/otxserver#236
=> Revert "Revert "new critical damage calculations""

path_10_9/data/talkactions/scripts/ban.lua
can ban players with the desired number of days, And create log
=> for use as described in command list

path_10_11/data/XML/gamestore.xml, path_10_11/src/game.cpp, path_10_11/src/gamestore.cpp, path_10_11/src/gamestore.h
implementing Wrappable items in Store
=> initial implementation of #292

path_8_6x/sources/game.cpp
Fixes #410 for 8.6(I didn't change the other versions because I can't test them)
=> Players will now be able to cast spells when muted

path_7_x/sources/tile.cpp
=> Otxserv2  [FIX]GM INVISIBLE BUG WHILE USING COMMAND /GOTO

path_8_6x/sources/combat.cpp
It wasn't tested, but it should fix #427
=> Fixes Crash

path_8_6x/sources/weapons.cpp
Fixes exponential critical hit damage multiplier and damage(#433).
(Needs to be extended to the other versions)
=> Fix Critical Hit Damage

path_7_x/data/items/74/items.xml, path_7_x/data/items/76/items.xml, path_7_x/data/items/77/items.xml, path_7_x/data/items/items.xml, path_8_1x/data/items/items.xml, path_8_5x/data/items/items.xml, path_8_6x/data/items/items.xml, path_8_7x/data/items/items.xml
*Fixes gold value not being used
*Fixes runes problems
=>  Fixes gold and runes

path_7_x/data/items/76/items.xml, path_7_x/data/items/77/items.xml, path_7_x/data/items/items.xml, path_8_1x/data/items/items.xml, path_8_5x/data/items/items.xml, path_8_6x/data/items/items.xml, path_8_7x/data/items/items.xml
*Some issue with the water was causing a high cpu usage when the server was starting, around 4% in my computer instead of the normal 0.3%
=>  Fixes water problems causing extra cpu usage

path_7_x/data/items/74/items.xml, path_7_x/data/items/76/items.xml, path_7_x/data/items/77/items.xml, path_7_x/data/items/items.xml, path_8_1x/data/items/items.xml, path_8_5x/data/items/items.xml, path_8_6x/data/items/items.xml, path_8_7x/data/items/items.xml
The blueberry bush was producing infinite blueberries
=> Fixes Blueberry bush

path_8_6x/sources/iologindata.cpp, path_8_6x/sources/iologindata.h, path_8_6x/sources/luascript.cpp, path_8_6x/sources/luascript.h
*This function allows the source to continue operating even when receiving a large amount of requests(it's a threaded function).It's also much faster than doPlayerSave, since it focuses on only saving the items.
=> Adds doPlayerSaveItems(cid)

path_8_6x/sources/game.cpp
This fixes #475, needs to be extended to the other versions but I don't have a server here to test them.
Also, feel free to use this on OTX3, since the bug also exists there =)
=> Fixes teleport bug

path_10_x/sources/weapons.cpp, path_7_x/sources/weapons.cpp, path_8_5x/sources/weapons.cpp, path_8_6x/sources/weapons.cpp, path_8_7x/sources/weapons.cpp
=>  Extends Critical Hit to fist attack

path_10_x/sources/protocollogin.cpp, path_7_x/sources/protocollogin.cpp, path_8_5x/sources/protocollogin.cpp, path_8_6x/sources/protocollogin.cpp, path_8_7x/sources/protocollogin.cpp
=> Fixes Cast/Live problem

path_10_x/data/globalevents/scripts/init.lua, path_7_x/data/globalevents/scripts/init.lua, path_8_5x/data/globalevents/scripts/init.lua, path_8_6x/data/globalevents/scripts/init.lua
Query to clear players broadcasting when starting up the server.
=> Updated cast system

path_8_6/src/protocollogin.cpp
https://github.com/mattyx14/otxserver/issues/552
=> Fix crash #552

path_8_6/src/house.cpp
Fix a possible problem, did not test if crashes, but a check is always good.
=> Fix a possible crash problem.

path_8_6/src/player.h
The bug works only in patch 8.6.
http://prntscr.com/ntx3ia
=> Problem in NPC Trade with infinity cap flag.

path_8_6/src/creature.cpp
this fixes the problem that hasCondition returned false if you used -1 in ticks for a condition (to make it infinite)
=> FIX TFS - fix hasCondition function by EvilHero90

path_8_6/src/luascript.cpp
added a separated function to parse loot (pushLoot)
=> TFS FIX - fix getLoot() crash by maattch

schema.sql
=> Add missing autoloot tables

data/actions/scripts/other/doors.lua, sources/container.cpp
=> Fix container #691

docs/luaFunctions, sources/luascript.cpp
Add optional params force and extend to doCreateNpc, like as used in doCreateMonster.
=> Add params extend and force to doCreateNpc

sources/msvc/TheOTXServer.vcxproj, sources/msvc/TheOTXServer.vcxproj.filters
Last commit (#737) didn't update msvc building configuration.
=> Add msvc project missing files

sources/databasemysql.cpp
change in the connect method of databasemysql.cpp removing the warning from MYSQL_OPT_RECONECT being a deprecated method that will be removed.
=> Update Connect, preventing warning

sources/player.cpp
modifying the autoloot functions, making them more readable and more performant.
=> Update autoloot methods

sources/player.cpp, sources/talkaction.cpp, sources/talkaction.h
a small update to the autoloot functions in talkaction, reducing code, and making it cleaner and more readable, removing repetitions
=> update autoloot functions
