path_7_x/sources/creature.cpp

Con esto se soluciona el debug y la CONDITION_INVISIBLE funciona correctamente, probado!
Aplica este cambio a todos los protocolos pues todos deben presentar la misma falla con los monsters con condition invis.

Fix CONDITION_INVISIBLE & debug

---

path_10_9/src/game.cpp

Player::getSkillLevel return int value, dividing any value below 100 will result in 0, this fixes the problem

Fix critical damage not working

---

path_10_9/data/modules/scripts/gamestore/init.lua

verifying cap before add items and avoid removing coins if the items were not delivered.
fixes #176

fixes in gameStore

---

path_10_9/data/lib/compat/compat.lua
path_10_9/src/creature.h
path_10_9/src/luascript.cpp
path_10_9/src/luascript.h
path_10_9/src/monster.cpp
path_10_9/src/monster.h

Creating dedicated method to set a creature's master that isn't linked with the convince behavior. This fixes mattyx14/otxserver#199

Creating dedicated method to set creature master

---

path_8_6/src/configmanager.cpp
path_8_6/src/configmanager.h
path_8_6/src/monster.cpp

Hello, I opened an issue #219 asking for this, I've done a good part of it, including float values (it is mainly used with x.x values to make a better balancing of monsters)
I'm having problems with **rateMonsterAttack** and **rateMonsterDefense** since **rateMonsterHealth** is working ok. 
I don't know about sources or C, i'm "happy" with the result taking this into account. Of course I want it working. But I just searched about including float and then some copy/paste/edit on 0.4/0.3.7 that had this function.
They probably changed how the damages are calculed on monsters (defense/attack) and even if it compiled ok, the damages won't change, even if I add a really high value just to test.

rateMonsterHealth, rateMonsterAttack & rateMonsterDefense OTX3

---

path_10_9/src/monster.cpp

This avoids players exploiting #276 for killing monsters without risk using large area runes from max range.
Fixes #276

Monster Seeing Range increased to 10 

---

path_10_11/data/modules/scripts/prey system/preysystem.lua

According to client 11.47, if the player is premium, it has the right of the prey slot to be unlocked. Adding this simple condition, the slot will be released if it is premium. And if it is not, the slot will remain locked.

Update unlocked prey slot if player has premium account

---

path_10_x/sources/game.cpp
path_7_x/sources/game.cpp
path_8_1x/sources/game.cpp
path_8_5x/sources/game.cpp
path_8_6x/sources/game.cpp
path_8_7x/sources/game.cpp

Fix easy to generate crash bug. You can invite yourself to Party when you are not in any party:
https://otland.net/threads/crash-party-tfs-0-4-8-60.258129/#post-2498323

Party self-invite crash bug fix

---

path_8_6x/sources/combat.cpp

Fixes monsters being able to cast beam spells through walls when targeting a player, example below:
https://gyazo.com/8d779c211c003b7ae2c83b132d598f43

Fixes monster beam casting through walls

---

path_8_6x/sources/protocolgame.cpp

Apparently there's some people using a packet editor program to manipulate the login packets and cause the server to be inaccessible.This is achieved by login in with an normal account and then trying to enter the game with a character that does not exist multiple times, causing the mysql Database to overload.
Note: This must be extended to the other versions(8.7x, 8.5x...) I currently can't test it on the other, that's why I haven't extended the fix, but it's safe to assume that the problem persist on the others too.

Fixes SQL Overload

---

path_8_6x/sources/combat.cpp
path_8_6x/sources/weapons.cpp
path_8_6x/sources/weapons.h

Scripted weapons with COMBAT_FORMULA_SKILL(example: viper star) now properly display critical hits

Scripted Weapons now display critical hits

---

path_8_6/data/events/scripts/player.lua

The problem occurs when you use classicEquipmentSlots, it happens as follows.
1 item in the left hand of two hands.
1 item in the arrow slot.
I try to move this item on the arrow to the right hand and the error in the `getSize()` function occurs, as it tries to pick up from a parent that is not a container.

Fix error using classicEquipmentSlots

---

path_8_6/src/iologindata.cpp

When insert to the database a value uint8_t it presents a special symbol, generating error in the console and consequently error when saving the player, this is a rather serious problem.

Fix query error using Visual Studio 2019

---

.travis.yml

add missing dependency libboost-filesystem

fix: travis-ci

---

path_8_6/src/game.cpp

By getting the CONDITION_INFIGHT condition even players in the protection zone could not leave the party

Verification to leave party in protection zone

---

sources/player.cpp

- I only realized it after previous pull request been merged
- Sorry, probably my text editor's autocomplete made this mistake

Fix wrong boolean to check classicAttackSpeed

---

data/startup/others/hireling_lib.lua

- Using FLAG_NOLIMIT when returning the hireling lamp to user's store inbox.
- Ignoring the inbox available slots in this case avoids a crash in the hireling_lib file when the user losing the house has a full store inbox.
This PR replicates the fix from opentibiabr/otservbr-global#809
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
hireling_lib.lua crashes on a specific scenario on server startup
Server startup must not crash
opentibiabr/canary#607
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration …

 Fix hireling_lib crash on server startup

---

sources/chat.cpp

How to reproduce: when you open a private channel and logout, this channel is never erased/deleted.
We need to call `deleteChannel()` instead of `it->second->closeChannel()`, so we erase the channel from the map and deallocate its memory, since it's dynamically allocated.
Also, an approach with better readability and performance.

Fix private channels memory leak

---

sources/spells.cpp

Not sure if I'm missing something here, but it seems that if you turn off the black skull system in the config, aggressive area spells just don't work at all. (branch `otxserv2`)
The patch in this PR appears to fix the issue (look at the surrounding code (`if (!needTarget)` block) and it's pretty obvious why it happens)
- Bug fix (non-breaking change which fixes an issue)
- Checked if aggressive area spells work on a local server both before and after this patch. After this patch, they work.
- [N/A] I checked the PR checks reports
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [N/A] I have added tests that prove my fix is effective or that my feature works

otxserv2: Fix aggressive area spells not working with black skull system off

---

sources/monster.cpp

If knight challenge the target, he can not run when the health is low. Is that make sense for everybody else? I do not know if that is relevant. But I think that is the actual behavior in Real Tibia today.
The "Challenge" spell not avoid target from running away with low health.
After cast "Challenge" the target will not run away with low health.
**Test Configuration**:
- Server Version:  Windows 10 (localhost)
- Client: 8.6
- Operating System: Windows 10

change fleeing behavior

---

data/items/items.xml

Corrects the action of going up and down stairs that were with floorchange eastalt, southalt
player tries to climb the stairs and nothing happens, when trying to go down he gets stuck in front of the stairs completely bugged.
go up and down the stairs correctly
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
- Server Version: 8.60
- Client: otcv8
- Operating System: Windows

 Fixes bug with stairs not going up or down

---

sources/player.cpp

fix: count arm only if it equiped on the right slot
